name: gltexture_plugin_example
description: Demonstrates how to use the gltexture_plugin plugin.

dependencies:
  flutter:
    sdk: flutter
  gltexture_plugin:
    path: ../

flutter:
  uses-material-design: true
