name: gltexture_plugin
description: Plugin that allow Flutter to communicate with a native Webview.
authors:
- ashawn <ashawnchang@gmail.com>

homepage: https://github.com/ashawn/gltexture_plugin
version: 0.1.0
maintainer: ashawn

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.gltexture_plugin
    pluginClass: GLTexturePlugin

dependencies:
  flutter:
    sdk: flutter
